export const types = [
    { name: 'Qualquer', value: 0 },
    { name: 'Normal', value: 1 },
    { name: 'Lutador', value: 2 },
    { name: 'Voador', value: 3 },
    { name: 'Venenoso', value: 4 },
    { name: 'Terra', value: 5 },
    { name: 'Pedra', value: 6 },
    { name: 'Inseto', value: 7 },
    { name: 'Fantasma', value: 8 },
    { name: 'Aço', value: 9 },
    { name: 'Fogo', value: 10 },
    { name: 'Água', value: 11 },
    { name: 'Grama', value: 12 },
    { name: 'Elétrico', value: 13 },
    { name: 'Psíquico', value: 14 },
    { name: 'Gelo', value: 15 },
    { name: 'Dragão', value: 16 },
    { name: 'Sombrio', value: 17 },
]